"""Suricata rule generator.

Produces one rule per IOC with monotonically-allocated SIDs. Suricata
doesn't natively match raw file hashes without the file-extract pipeline,
so hashes are skipped here (Sigma covers the EDR-side detection).
"""

from __future__ import annotations

from urllib.parse import urlparse

from ioc_hunter.core.types import IOCType
from ioc_hunter.rules._common import filter_by_severity
from ioc_hunter.scorer import IOCVerdict
from ioc_hunter.sources.base import Verdict


def _escape_content(value: str) -> str:
    """Escape characters that have meaning inside a Suricata `content:` value."""
    # Backslash first, then quote, then semicolon, then pipe.
    return value.replace("\\", "\\\\").replace('"', '\\"').replace(";", "\\;").replace("|", "\\|")


def _rule_for_ip(ioc_value: str, msg: str, sid: int) -> str:
    return (
        f"alert ip any any -> {ioc_value} any "
        f'(msg:"{msg}"; sid:{sid}; rev:1; classtype:trojan-activity;)'
    )


def _rule_for_domain(domain: str, msg: str, sid: int) -> str:
    return (
        f"alert dns any any -> any any "
        f'(msg:"{msg}"; dns.query; content:"{_escape_content(domain)}"; '
        f"nocase; sid:{sid}; rev:1; classtype:trojan-activity;)"
    )


def _rule_for_url(url: str, msg: str, sid: int) -> str | None:
    parsed = urlparse(url)
    host = parsed.hostname
    if not host:
        return None
    path = parsed.path or "/"
    if parsed.params:
        path = f"{path};{parsed.params}"
    if parsed.query:
        path = f"{path}?{parsed.query}"
    return (
        f"alert http any any -> any any "
        f'(msg:"{msg}"; http.host; content:"{_escape_content(host)}"; nocase; '
        f'http.uri; content:"{_escape_content(path)}"; nocase; '
        f"sid:{sid}; rev:1; classtype:trojan-activity;)"
    )


def _rule_for_verdict(v: IOCVerdict, sid: int) -> str | None:
    label = v.ioc.type.value
    msg = f"IOC Hunter: {label} {v.ioc.value} ({v.verdict.value})"
    if v.ioc.type is IOCType.IPV4 or v.ioc.type is IOCType.IPV6:
        return _rule_for_ip(v.ioc.value, msg, sid)
    if v.ioc.type is IOCType.DOMAIN:
        return _rule_for_domain(v.ioc.value, msg, sid)
    if v.ioc.type is IOCType.URL:
        return _rule_for_url(v.ioc.value, msg, sid)
    return None


def to_suricata(
    verdicts: list[IOCVerdict],
    *,
    sid_start: int = 1_000_001,
    min_verdict: Verdict = Verdict.MALICIOUS,
) -> str:
    """Render Suricata rules for every malicious IOC, one per line."""
    bad = filter_by_severity(verdicts, min_verdict)
    if not bad:
        return ""

    lines: list[str] = ["# Generated by ioc-hunter."]
    sid = sid_start
    for v in bad:
        rule = _rule_for_verdict(v, sid)
        if rule is None:
            continue
        lines.append(rule)
        sid += 1
    return "\n".join(lines)
